
BSCFLAGS=-aggressive-conditions -show-schedule -keep-fires -p +:../paclib -DN_VALUE=4

XBSVDIR=../../xbsv
DBNDIR=..
DBNTOPBSV=../testmm/Top.bsv
TESTCPPFILES=../testmm/testmm.cpp
include ../Makefile.dbn
