
BSCFLAGS=-aggressive-conditions -show-schedule -keep-fires -p +:../paclib

XBSVDIR=../../xbsv
DBNDIR=..
DBNTOPBSV=    ../testmm/Top.bsv
TESTCPPFILES= ../testmm/testmm.cpp
XBSVFLAGS = -D J_VALUE=4 -D K_VALUE=2 -D N_VALUE=2
include ../Makefile.dbn
